### ISSUE TITLE
Close button (X) in the title bar missing after changing themes (EDDLite 2.2.0)

### ISSUE THREAD

**Issue by mIRCon** [EDDiscovery/EDDLite#11]
If you change theme to EDSM Arial Narrow, then exit EDDLite and start it again and change theme to EDSM you would get missing  close button (X) in the title bar.
Sometimes it can happen just by changing themes but can't 100% reproduce it like I can using above described steps.

Once "X" is missing it can be shown only by selecting either EDSM Arial Narrow or Easy Dark OR you can select wanted theme and exit EDDLite using other means  (alt+F4, using taskbar close or  alt+space and selecting close). Once you start it again it will load last used theme properly.

Discussed this "behaviour" on Discord and some examples of look and even a video can be checked out on these links:
https://discord.com/channels/151028492048269313/722068308668448779/969644538022998087

https://discord.com/channels/151028492048269313/722068308668448779/969657234785173515

As discussed on discord, removing %localappdata%\EDDLite  doesn't solve the issue so it's not related to EDDUser.sqlite corruption or similar cause.

**Comment by Eahlstan** [comment]
I tried to reproduce this, but I couldn't.

**Comment by robbyxp1** [comment]
Changing themes sometimes works and does not - its a winform thing that it does not always repaint properly.

i would be interested if after a restart it was still missing..

**Comment by mIRCon** [comment]
EDSM Arial Narrow and Easy Dark are "immune" to the issue when you keep changing themes in the same EDDLite session which makes things more interesting. They never failed no matter how many times I switched in and out of them.

also for the record: Windows 10 20H2 build with all the current/latest updates and .NET 4.8 with the latest KBs.

EDDLite restart "fixes" the issue so once you exit the program and start it again X will be properly drawn and visible element of the GUI so it's not a deal breaking issue anyway.

**Comment by robbyxp1** [comment]
I'll double check i do all the stuff in  EDDLite that I do in EDD to make it update the UI.

**Comment by robbyxp1** [comment]
Fix hopefully applied
