### ISSUE TITLE
Journal sync to Inara and EDSM not working

### ISSUE THREAD

**Issue by lal309** [EDDiscovery/EDDLite#14]
Running Odyssey on PC, EDDLite  v2.6.0, pointed the program towards my journal files, added API keys to Inara and EDSM and enabled "Sync to Inara" and "Sync to EDSM".

Inara is only receiving current star system location and commander credits information. EDSM is not receiving any data at all. According to EDDLite trace logs, Inara and EDSM are responding with 200 OK (see below):

- [2024-02-19T15:08:58.027Z] HTTP POST to https://inara.cz/inapi/v1/ Thread Inara Journal Sync
- [2024-02-19T15:08:58.027Z] HTTP POST to https://inara.cz/inapi/v1/ Response OK

- [2024-02-19T20:23:32.150Z] HTTP POST to https://www.edsm.net/api-journal-v1 Thread EDSM Journal Sync
- [2024-02-19T20:23:32.374Z] HTTP POST to https://www.edsm.net/api-journal-v1 Response OK

I cant seem to locate a "Force Sync" type of functionality so I've had to disable and re-enable the "Sync to Inara/EDSM" check boxes to force EDDLite to re-read journal files and attempt to send data to these two integrations (without success).

**Comment by Eahlstan** [comment]
For Inara: That's how Inara works. A few things can be updated using their API, but for most things you have to  log in on their site and allow them to connect to Frontier directly.

For EDSM: Impossible to say anything without the full logs. Are you actively playing while EDDLite is running?

**Comment by lal309** [comment]
Inara: my apologies then. 

EDSM: Yes, I’m running EDDLite before launching the game on Steam. Which log file(s) are needed and how can I make them available/easily accessible to you?

**Comment by lal309** [comment]
@Eahlstan here are the logs that I found in the APPDATA local folder. I did my best to redact all sensitive information and noted it as *REDACTED within each line.

[logs.zip](https://github.com/EDDiscovery/EDDLite/files/14339091/logs.zip)

**Comment by Eahlstan** [comment]
Can you please describe your setup?
OS, where you installed what, ...
And is there any chance you're playing the Legacy version?

**Comment by klightspeed** [comment]
This looks like it might be a bug in wine-mono (https://github.com/mono/mono/issues/21677) where the workaround (https://github.com/EDDiscovery/EliteDangerousCore/pull/125) hasn't made it to EDDLite yet.

Does this work if you try running EDDLite directly under Mono instead of from within Wine?

**Comment by lal309** [comment]
@Eahlstan not running Legacy. I'm running Odyssey.
Here's my setup: 

Fedora 39 KDE (well technically Nobara 39 but it's Fedora under the hood).
Kernel 6.7.0-204.fsync.fc39.x86_64 (64-bit)
NVIDIA GeForce GTX 1080 Ti
Intel® Core™ i5-6600K
16GB RAM
Wine Staging 8.20
Steam version 1705108172
Game running under Proton 8.0-5
Elite Dangerous Launcher version 1.7.6926.10 FD 
Elite Dangerous: Odyssey FORD-FDEV-D0-1000
Installation path = default Steam path

**Comment by lal309** [comment]
@klightspeed here are the steps I took this morning after reading your reply

1. Launch EDDLite as normal (desktop shortcut)
2. Removed check mark "Send Event Information to EDDN"
3. Removed check mark "Sync to Inara"
4. Verified EDSM API Key and verified "Sync to EDSM" was enabled.
5. Saved all settings and watched the output section
6. I noticed it did not tell me that it send X amount of events to EDSM. When the Inara sync was enabled it would tell me that it "Sent X amount of event to Inara".
7. Exited EDDLite
8. Launched a terminal and navigated to the EDDLite.exe path
9. Launch EDDLite using mono (mono ./EDDLite.exe)
10.  The command complained that I did not have mono-core installed so I installed that dependency and relaunched the mono command
11. EDDLite did not look quite right (spacing, small fonts, UI carshes, etc.)
12. My commander was not configured and showed the default. Clicked on the commander and reconfigured the path to the journal files, enabled "Include subfolders", entered EDSM API key, enabled "Sync to EDSM", and disabled "Send Event Information to EDDN".
13. EDDLite got stuck and unresponsive, forced the window to close out  and relaunch EDDLite through mono.
14. Commander information was saved, EDSM sync was enabled, output section seems to be reading events from journal files but the last message shown is "Finished Reading Journals" (still no "Sent X amount of events to EDSM" type of message).  
15. Exited EDDLite through mono
16. Relaunched EDDLite  as normal (desktop shortcut)
17. Output section shows events from journals but no indication that it sent events to EDSM.
18. After ~30 minutes, logged in to EDSM > Profile > My Flight Log > saw no recent traveled systems.

**Comment by klightspeed** [comment]
Steps 1-6 and 16-18 would not have worked as there is currently a bug in mono that results in the `FileSystemWatcher` returning an invalid full path when running under Windows (and Wine).

Note that EDDLite running under Mono under Linux will store its profile in `~/.local/share/EDDLite`, while running under Wine will store its profile in `~/.wine/drive_c/Users/${username}/AppData/Local/EDDLite`, thus settings not carrying over between the two.

**Comment by klightspeed** [comment]
Another option might be to try using winetricks to install the .NET Framework 4.8 Runtime (dotnet48) into the wine prefix.

**Comment by lal309** [comment]
I assume (based on your comment above) that since EDD has the fix applied to the codebase then fix will be ported to EDDLite soon?

**Comment by lal309** [comment]
> Another option might be to try using winetricks to install the .NET Framework 4.8 Runtime (dotnet48) into the wine prefix.

@klightspeed  based on your suggestion I created a brand new 64bit wine prefix (EDDLite would not run/install under a 32bit prefix), installed dotnet48 (which also installed dotnet40, I assume as a dependency of dotnet48), installed corefonts and tahoma fonts just in case, ran winecfg and selected "Windows Version" as "Windows 10", then ran EDDLite installer. Finished installation and launched EDDLite in two different ways:

- WINEPREFIX=~/wine/eddlite wine ~/wine/eddlite/drive_c/Program\ Files/EDDLite/EDDLite.exe
- WINEPREFIX=~/wine/eddlite mono ~/wine/eddlite/drive_c/Program\ Files/EDDLite/EDDLite.exe 

EDDLite is reading the journals but still no updated data in EDSM.

If you have further suggestions please let me know.

**Comment by klightspeed** [comment]
> EDDLite is reading the journals but still no updated data in EDSM.

I presume that in both cases you tried jumping between systems while EDDLite was running?  If I recall correctly, unlike EDDiscovery, EDDLite will only send events that are logged while it is running, and will not send any events logged before the current run.

**Comment by lal309** [comment]
Well actually I did not know that. I assumed that since it could read the files, it would send the event data to EDSM (even if I wasn't running the game). After sending my last reply, I started playing ED while EDDLite was running and now I see outputs such as "Sent 5 Events to EDSM". I logged in to EDSM and I can also see the systems I visited since installing EDDLite in the new wine prefix (Travel Map). Any other spots I can check to ensure EDDLite is sending updated data? Unfortunately, prior to discovering EDDLite, I had manually imported journal files into EDSM therefore things like rank, balance, fleet, etc. may be showing from the manual import rather than EDDLite.

**Comment by klightspeed** [comment]
Uploading journals to EDSM calls the same API endpoint that EDDLite uses to submit journals to EDSM, so there should be no harm uploading any missed journals via EDSM's journal uploader.

**Comment by lal309** [comment]
> Uploading journals to EDSM calls the same API endpoint that EDDLite uses to submit journals to EDSM, so there should be no harm uploading any missed journals via EDSM's journal uploader.

Wouldn’t this cause duplicate entries in EDSM?

**Comment by lal309** [comment]
Is the donet48 in a standalone prefix a workaround or can we expect a more “permanent fix” in a future EDDLite release?

**Comment by klightspeed** [comment]
> Wouldn’t this cause duplicate entries in EDSM?

EDSM generally doesn't create duplicate entries if the same journal entries are sent again.  I think it was also smart enough to merge the new journal-based travel entries with the old netlog-based travel entries.

**Comment by klightspeed** [comment]
[EDDLite 2.7.0](https://github.com/EDDiscovery/EDDLite/releases/tag/Release_2.7.0) should fix this issue.
