### ISSUE TITLE
many (Adding Unknown event to EDSM journal sync) in journal window

### ISSUE THREAD

**Issue by nulls-matter** [EDDiscovery/EDDLite#5]
Many `Adding Unknown event to EDSM journal sync` and unformatted commands being displayed as raw text `{"timestamp":"2021-06-07T18:16:10Z","event":"BackpackChange","Removed":[{"Name":"amm_grenade_frag","Name_Localised":"Frag Grenade","OwnerID":0,"Count":1,"Type":"Consumable"}]}`
![image](https://user-images.githubusercontent.com/57365320/121069782-c2a1ed80-c782-11eb-968e-4c98a7bc60ad.png)

**Comment by robbyxp1** [comment]
EDDLite will be updated once the frontier journal is stable. thanks for the report.

**Comment by robbyxp1** [comment]
Wed release
