### ISSUE TITLE
EDDLite v2.0.0.0 Error

### ISSUE THREAD

**Issue by randomjoule** [EDDiscovery/EDDLite#9]
### Exception Details:
>EDDLite v2.0.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Der Wert darf nicht NULL sein.
>Parametername: key
>   bei System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>   bei System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
>   bei EliteDangerousCore.Inara.InaraSync.NewEntryList(HistoryEntry he, Dictionary`2 mcmr) in C:\Code\EDDLite\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:Zeile 592.
>   bei EliteDangerousCore.Inara.InaraSync.NewEvent(Action`1 logger, HistoryEntry he, Dictionary`2 mcmr) in C:\Code\EDDLite\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:Zeile 77.
>   bei EDDLite.EDDLiteForm.HistoryEvent(HistoryEntry he, Boolean stored, Boolean recent) in C:\Code\EDDLite\EDDLite\EDDLiteForm.cs:Zeile 449.
>   bei EDDLite.EDDLiteController.Entry(JournalEntry je, Boolean stored, Boolean recent) in C:\Code\EDDLite\EDDLite\EDDLiteController.cs:Zeile 165.
>   bei EliteDangerousCore.EDJournalUIScanner.IssueEvents(Tuple`2 entries) in C:\Code\EDDLite\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:Zeile 146.
>===== END =====
>```

**Comment by Eahlstan** [comment]
Looks like this issue: https://github.com/EDDiscovery/EDDiscovery/issues/3242

We never got journals from that user, if you could provide one that causes this error, please.

**Comment by robbyxp1** [comment]
Commenting on the eddiscovery one

**Comment by robbyxp1** [comment]
Closing, same bug as the EDD one. We will address. thanks

**Comment by robbyxp1** [comment]
Second thoughts - randomjoule - do you have the journal .log file where this happened in?  if so, and you are willing to share, you can just copy it into a comment here, or DM me privately on discord.

**Comment by randomjoule** [comment]
[Journal.2022-04-08T114044.01.log](https://github.com/EDDiscovery/EDDLite/files/8463725/Journal.2022-04-08T114044.01.log)

**Comment by Eahlstan** [comment]
Thanks for the journal.

Looks like Frontier changed the scheme of an event and didn't tell anyone about it.

**Comment by robbyxp1** [comment]
thank you - the tip code now works with this.
